### ISSUE TITLE
Master checklist

### ISSUE THREAD

**Issue by andrewadare** [andrewadare/rolling-blackout#1]
### Primary CPU (RPi3)
 - [ ] Serial com with LIDAR unit
 - [ ] Serial (or wireless?) com with IMU
 - [ ] Serial com with steering MCU
 - [ ] Integration of IMU, LIDAR, encoder, and steering feedback into main program

### High-level software
 - [ ] FastSLAM (only EKF-SLAM fully implemented)
 - [ ] How to integrate additional sensor data (IMU, encoder, steering angle)?
 - [ ] Formatting/serialization of telemetry output
 - [ ] Telemetry server (probably WebSockets)

### LIDAR sensor/control unit
 - [ ] connection to RPi
 - [ ] mount unit (location? how to attach?)
 - [ ] angle calibration (no absolute measurement; relies on stepper counts)

### Internal communication
 - [ ] Decide on protocol and networking. Pub-sub vs. synchronous master/slave
 - [ ] MQTT?: mosquitto server, mqttwarn client
 - [ ] Is timing synchronization needed? Do we need an RTC?

### Steering control
 - [ ] Steering angle feedback
 - [ ] Homing (need limit switches or Hall sensors)
 - [ ] Read quadrature encoder

### Motor control
 - [ ] Interrupt handler for telemetry input (kill button)
 - [ ] H-bridge (oleg)

### Telemetry
 - [ ] Access point: router vs hostapd on RPi + antenna
 - [ ] Kill switch
 - [ ] Wireless TX
 - [ ] Wireless RX

### Remote monitoring software
 - [ ] Vehicle orientation
 - [ ] Steering angle
 - [ ] Odometry and speed
 - [ ] LIDAR: range and angle output
 - [ ] Map from SLAM
 - [ ] Kill button (separate 2.4 GHz signal?)
